InsiderNepalApp/InsiderNepalApp/Controllers/AdsController.cs
using InsiderNepalApp.Data;
using InsiderNepalApp.Extensions;
using InsiderNepalApp.Mapper;
using InsiderNepalApp.Models;
using InsiderNepalApp.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace InsiderNepalApp.Controllers
{
    public class AdsController : Controller
    {

        private readonly InsiderNepalDbContext _adx;
        public AdsController(InsiderNepalDbContext adx)
        {
            _adx = adx;
        }

        //to show the ads
        public IActionResult Index()
        {
            var adsi = _adx.AdsModel.ToList();
            adsi.Reverse();
            var adsiVM = adsi.ToViewModel();
            return View(adsiVM);
        }

        //get for adding new add
        public IActionResult AddAds()
        {
            return View();
        }


        //post method for adding new ads
        [HttpPost]
        public IActionResult AddAds(AdsVM advm)
        {
            if (advm == null || !ModelState.IsValid)
            {
                // return View("Error", new ErrorViewModel { RequestId = "Register News" });
                return View();
            }

            string avatarPath = advm.AdsAvatar.SaveAdsImage();
            var adsmodel = advm.ToModel();
            adsmodel.ImageUrl = avatarPath;
            try
            {
                _adx.Add(adsmodel);
                _adx.SaveChanges();
                TempData["msg"] = "Added Successfully";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["msg"] = "could not be added !!!";

            }
            return View();
        }


        // for editing ads
        public IActionResult EditAds(int id)
        {
            var ads = _adx.AdsModel.Find(id);
            var adsVM = ads?.ToViewModel();
            return View(adsVM);
        }

        [HttpPost]
        public IActionResult EditAds(AdsVM adsVM)
        {
            if (adsVM == null || !ModelState.IsValid)
            {
                return View("Error", new ErrorViewModel { RequestId = "Update Ads not successful" });

            }
            var ads = adsVM.ToModel();
            if (adsVM.AdsAvatar is not null)
            {
                var path = adsVM.AdsAvatar.SaveAdsImage();
                ads.ImageUrl = path;
            }
            try
            {
                _adx.AdsModel.Update(ads);
                _adx.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["msg"] = "Could not be added";
                return View();
            }
        }




        // for deleting and updating news
        public IActionResult DeleteConfirmAds(int id)
        {
            var ads = _adx.AdsModel.Find(id);
            var adsVM = ads?.ToViewModel();
            return View(adsVM);
        }

        [HttpPost]
        public IActionResult DeleteAds(AdsVM adsVM)
        {
            try
            {
                var adstry = _adx.AdsModel.Find(adsVM.AdsId);
                _adx.AdsModel.Remove(adstry);
                _adx.SaveChanges();

                //var ads = adsVM.ToModel();
                //if (ads != null)
                //{
                //    _adx.AdsModel.Remove(ads);
                //    _adx.SaveChanges();
                //}

            }
            catch (Exception ex)
            {

            }
            return RedirectToAction("Index");
        }

    }
}

InsiderNepalApp/InsiderNepalApp/Controllers/CultureController.cs
using InsiderNepalApp.Data;
using InsiderNepalApp.Extensions;
using InsiderNepalApp.Mapper;
using InsiderNepalApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InsiderNepalApp.Controllers;

[Authorize(Roles ="Admin")]
public class CultureController : Controller
{
    private readonly InsiderNepalDbContext _cdx;

    public CultureController(InsiderNepalDbContext cdx)
    {
        _cdx = cdx;
    }

    public IActionResult Index()
    {
        var cNews = _cdx.CultureNews.ToList();
        cNews.Reverse();
        var cNewsVM = cNews.ToViewModel();
        return View(cNewsVM);
    }

    // Add Culture News 
    public IActionResult AddCultureNews()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddCultureNews(CultureNewsVM cNewsVM)

    {
        if(cNewsVM == null || !ModelState.IsValid)
        {
            return View();
        }
        string avatarPath = cNewsVM.Avatar.SaveCulutreAndLifestyleImage();
        var cNews = cNewsVM.ToModel();
        cNews.ImageUrl = avatarPath;
        try
        {
            _cdx.Add(cNews);
            _cdx.SaveChanges();
            TempData["msg"] = "Added Successfully";
            return RedirectToAction("index");
        }
        catch(Exception ex)
        {
            TempData["msg"] = "could not be added !!";
        }
        return View();
    }

    //Editing
    public IActionResult EditCultureNews(int id)
    {
        var cNews = _cdx.CultureNews.Find(id);
        var cNewsVM = cNews.ToViewModel();
        return View(cNewsVM);
    }

    [HttpPost]
    public IActionResult EditCultureNews(CultureNewsVM cNewsVM)
    {
        if(cNewsVM == null || !ModelState.IsValid)
        {
            return View();
        }
        
        var cNews = cNewsVM.ToModel();
        
        if(cNewsVM.Avatar is not null)
        {
            var path = cNewsVM.Avatar.SaveCulutreAndLifestyleImage();
            cNews.ImageUrl = path;
        }
        try
        {
            _cdx.CultureNews.Update(cNews);
            _cdx.SaveChanges();
            return RedirectToAction("index");
        }
        catch(Exception ex)
        {
            TempData["msg"] = "Could not be updated";
            return View();
        }
        return View();
    }

    // For Deleting

    public IActionResult DeleteConfirmCN(int id)
    {
        var cNews = _cdx.CultureNews.Find(id);
        var cNewsVM = cNews.ToViewModel();
        return View(cNewsVM);
    }

    [HttpPost]
    public IActionResult DeleteCN(CultureNewsVM cNewsVM)
    {
        try
        {
            var cNews = cNewsVM.ToModel();
            if(cNews !=null)
            {
                _cdx.Remove(cNews);
                _cdx.SaveChanges();
            }
        }
        catch (Exception ex)
        {
            TempData["msg"] = "Could not be deleted";
            return View();
        }
        return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public IActionResult ReadCultureNews()
    {
        var gnews = _cdx.CultureNews.ToList();
        gnews.Reverse();

        var gnewsVM = gnews.ToViewModel();

        var ads = _cdx.AdsModel.ToList();
        var adsVM = ads.ToViewModel();
        CultureAdsVM gav = new()
        {
            CultureNewVM = gnewsVM,
            AdsVM = adsVM,
        };

        return View(gav);
    }

    [AllowAnonymous]
    public IActionResult ShowCultureInDetail(int id)
    {
        var gnews = _cdx.CultureNews.Where(x => x.CultureNewsId == id).ToList();
        var gnewsVM = gnews.ToViewModel();

        var ads = _cdx.AdsModel.ToList();
        var adsVM = ads.ToViewModel();

        CultureAdsVM gav = new()
        {
            CultureNewVM = gnewsVM,
            AdsVM = adsVM
        };

        return View(gav);
    }

}

InsiderNepalApp/InsiderNepalApp/Controllers/GlobalNewsController.cs
using InsiderNepalApp.Data;
using InsiderNepalApp.Extensions;
using InsiderNepalApp.Mapper;
using InsiderNepalApp.Models;
using InsiderNepalApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Identity.Client;

namespace InsiderNepalApp.Controllers;

[Authorize(Roles = "Admin")]
public class GlobalNewsController : Controller
{
    private readonly InsiderNepalDbContext _gdx;
    public GlobalNewsController(InsiderNepalDbContext gdx)
    {
        _gdx = gdx;
    }
    public IActionResult Index()
    {
        var globalNews = _gdx.GlobalNews.ToList();
        globalNews.Reverse();
        var globalNewsVM = globalNews.ToViewModel();
        return View(globalNewsVM);
    }

    public IActionResult AddGlobalNews()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddGlobalNews(GlobalNewsVM globalNewsVM)
    {
        if (globalNewsVM == null || !ModelState.IsValid)
        {
            //return View("Error", new ErrorViewModel {RequestId = "Registering Global News is not possible !!"});
            return View();
        }
        string imagePath = globalNewsVM.Avatar.SaveGlobalImage();
        var globalNews = globalNewsVM.ToModel();
        globalNews.ImageUrl = imagePath;

        try
        {
            _gdx.Add(globalNews);
            _gdx.SaveChanges();
            TempData["msg"] = "Added Successfully";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["msg"] = "could not be added !!";
        }
        return View();
    }


    // for editing 

    public IActionResult EditGlobalNews(int id)
    {
        var gNews = _gdx.GlobalNews.Find(id);
        var gNewsVM = gNews.ToViewModel();
        return View(gNewsVM);
    }

    [HttpPost]
    public IActionResult EditGlobalNews(GlobalNewsVM globalNewsVM)
    {
        if (globalNewsVM == null || !ModelState.IsValid)
        {
            return View("Error", new ErrorViewModel { RequestId = "Update Global news not successful" });
        }

        var gNews = globalNewsVM?.ToModel();
        if (globalNewsVM?.Avatar != null)
        {
            var path = globalNewsVM.Avatar.SaveGlobalImage();
            gNews.ImageUrl = path;
        }
        try
        {
            _gdx.GlobalNews.Update(gNews);
            _gdx.SaveChanges();
            return RedirectToAction("Index");
        }
        catch (Exception ex) { }
        {
            TempData["msg"] = "could not be added";
            return View();
        }

    }
    //for deleting

    public IActionResult DeleteConfirm(int id)
    {
        var gnews = _gdx.GlobalNews.Find(id);
        var gnewsVM = gnews.ToViewModel();
        return View(gnewsVM);
    }

    [HttpPost]
    public IActionResult DeleteGlobalNews(GlobalNewsVM globalNewsVM)
    {
        try
        {
            var gnews = globalNewsVM.ToModel();
            if (gnews != null)
            {
                _gdx.GlobalNews.Remove(gnews);
                _gdx.SaveChanges();
            }
        }
        catch (Exception ex)
        {

        }
        return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public IActionResult ReadGlobalNews()
    {
        var gnews = _gdx.GlobalNews.ToList();
        gnews.Reverse();

        var gnewsVM = gnews.ToViewModel();

        var ads = _gdx.AdsModel.ToList();
        var adsVM = ads.ToViewModel();
        GlobalAdsVM gav = new()
        {
            GlobalNewsVM = gnewsVM,
            AdsVM = adsVM,
        };

        return View(gav);
    }

    [AllowAnonymous]
    public IActionResult ShowGlobalInDetail(int id)
    {
        var gnews = _gdx.GlobalNews.Where(x=>x.GlobalId == id).ToList();
        var gnewsVM = gnews.ToViewModel();

        var ads = _gdx.AdsModel.ToList();
        var adsVM = ads.ToViewModel();

        GlobalAdsVM gav = new()
        {GlobalNewsVM = gnewsVM,
            AdsVM = adsVM};

        return View(gav);
    }
}

InsiderNepalApp/InsiderNepalApp/Controllers/JournalController.cs
using Microsoft.AspNetCore.Mvc;

namespace InsiderNepalApp.Controllers
{
    public class JournalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

InsiderNepalApp/InsiderNepalApp/Views/Shared/_Layout.cshtml
@using InsiderNepalApp.Areas.Identity.Data;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<InsiderNepalAppUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InsiderNepalApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InsiderNepalApp.styles.css" asp-append-version="true" />
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-toggleable navbar-light box-shadow border-bottom fixed-top  pb-0 mb-5" style="display:flex; flex-wrap:wrap; background-color:rgb(11,35,81); padding-left:10px;">
        <div class="navbarHome">
            @if (User.IsInRole("Admin"))
            {
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="AdminPanel">InsiderNepalApp</a>
            }
            else
            {
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">InsiderNepalApp</a>

            }
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon text-white"><img src="~/images/Journal/ham.png" /></span>
        </button>
        <div class="collapse navbar-collapse text-white">
            <div class="navbarTopics">
                <ul class="navbar-nav flex-grow-1">

                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="AdminPanel"><i class="fa-solid fa-house"></i></a>
                        }
                        else
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house"></i></a>
                        }
                    </li>

                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="NationalNews" asp-action="Index">National</a>
                        }
                        else
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="NationalNews" asp-action="ReadNationalNews">National</a>
                        }
                    </li>
                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="GlobalNews" asp-action="Index">Global</a>

                        }
                        else
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="GlobalNews" asp-action="ReadGlobalNews">Global</a>
                        }
                    </li>
                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="BussinessNews" asp-action="Index">Business</a>
                        }
                        else
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="BussinessNews" asp-action="ReadBussinessNews">Business</a>

                        }
                    </li>
                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="Journal" asp-action="Index">Journal</a>
                        }
                        else
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="Journal" asp-action="Index">Journal</a>
                        }
                    </li>
                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="Culture" asp-action="Index">Culture&LifeStyle</a>
                        }
                        else
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="Culture" asp-action="ReadCultureNews">Culture&LifeStyle</a>
                        }
                    </li>

                    <li class="nav-item">
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="Ads" asp-action="Index">Ads</a>
                        }
                    </li>

                </ul>
                <div style="padding-top:5px; position:absolute; top:0; right:80px;">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </nav>



    <div class="container-fluid overflow-hidden p-5">
        <main role="main" class="mt-5 pt-2 mb-5">
            @RenderBody()

        </main>
    </div>


    <!-- Footer -->

    <footer class="text-center text-lg-start text-muted py-1" style="position:relative; width:100vw; bottom:0; background-color:rgb(11,35,81); ">
        <!-- Content -->
        <!-- Section: Social media -->
        <!-- Section: Social media -->
        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5 text-white">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <div class="newsTopic">
                            <h6 class="text-uppercase fw-bold mb-4 text-white">
                                About Us
                            </h6>
                        </div>
                        <p class="text-white">
                            <a href="#!" class="text-reset">About the Post</a>
                        </p><p class="text-white">
                            <a href="#!" class="text-reset">Masthead</a>
                        </p><p class="text-white">
                            <a href="#!" class="text-reset">Integrity</a>
                        </p><p class="text-white">
                            <a href="#!" class="text-reset">Workplace harrassment</a>
                        </p><p class="text-white">
                            <a href="#!" class="text-reset">Policies</a>
                        </p>
                        @* <p>
                        InsiderNepal is a news channel established in 2012.
                        Our goal is to provide insightful news and information about Nepal and Global.
                        We are dedicated to deliver accurate and timely news
                        that informs and empowers our audience.
                        </p>*@
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <div class="newsTopic">
                            <h6 class="text-uppercase fw-bold mb-4 text-white">
                                Read Us
                            </h6>

                        </div>
                        <p class="text-white">
                            <a href="#!" class="text-reset"><i class="fa-solid fa-truck me-2"></i>Home Delivery</a>
                        </p>
                        <p class="text-white">
                            <a href="#!" class="text-reset"><i class="fa-solid fa-mobile-screen me-2"></i>EPaper</a>
                        </p>

                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4 text-white">
                        <!-- Links -->
                        <div class="newsTopic">
                            <h6 class="text-uppercase fw-bold mb-4 text-white">
                                Social Media
                            </h6>
                        </div>
                        <p class="text-white">

                            <a href="#!" class="text-reset">
                                <i class="fa-brands fa-facebook fa-lg me-2"></i>Facebook
                            </a>
                        </p>
                        <p class="text-white">
                            <a href="#!" class="text-reset">
                                <i class="fa-brands fa-twitter me-2"></i>Twitter
                            </a>
                        </p>
                        <p class="text-white">
                            <a href="#!" class="text-reset">
                                <i class="fa-brands fa-square-instagram me-2"></i>Instagram
                            </a>
                        </p>
                        <p class="text-white">
                            <a href="#!" class="text-reset">
                                <i class="fa-brands fa-youtube me-2"></i>Youtube
                            </a>
                        </p>
                        <p class="text-white">
                            <a href="#!" class="text-reset">
                                <i class="fa-brands fa-tiktok me-2"></i>Tiktok
                            </a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4 text-white">
                        <!-- Links -->
                        <div class="newsTopic">

                            <h6 class="text-uppercase fw-bold mb-4">Contact Us</h6>
                        </div>
                        <p><i class="fa-solid fa-location-dot me-3"></i>Nayamarga,Tinkune Kathmandu, Nepal</p>
                        <p class="text-white">
                            <i class="fa-solid fa-envelope me-2"></i>
                            insidernepal@gmail.com
                        </p>
                        <p><i class="fa-solid fa-phone me-3"></i> +977-9867676543</p>
                        <p><i class="fa-solid fa-phone me-3"></i>+ 01 234 567</p>
                    </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->
        <!-- Copyright -->
        <div class="text-center p-4 text-white" style="background-color:rgb(11,35,81);">
            © 2023 Copyright:
            <a class="text-reset fw-bold text-white" href="https://mdbootstrap.com/">InsiderNepal.com</a>
        </div>
        <!-- Copyright -->
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>