InsiderNepalApp/InsiderNepalApp/Models/NationalNews.cs
using System.ComponentModel.DataAnnotations;

namespace InsiderNepalApp.Models
{
    public class NationalNews
    {
        // needed fields: Id, Title, Author, PublishData, Content, ImageUrl

        [Key]
        public int NationalNewsId { get; set; }

        public string? Title { get; set; }

        
        public string? Author { get; set; }


       
        public DateTime PublishDateTime { get; set; }

      
        public string? Content { get; set; } 

      
        public string? ImageUrl { get; set; }

    }
}

InsiderNepalApp/InsiderNepalApp/Controllers/NationalNewsController.cs
using InsiderNepalApp.Data;
using InsiderNepalApp.Extensions;
using InsiderNepalApp.Mapper;
using InsiderNepalApp.Models;
using InsiderNepalApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace InsiderNepalApp.Controllers
{
    [Authorize(Roles ="Admin")]
    public class NationalNewsController : Controller
    {
        private readonly InsiderNepalDbContext _ctx;
        public NationalNewsController(InsiderNepalDbContext ctx)
        {
            _ctx = ctx;
        }

        public IActionResult Index() 
        {
            try
            {
            var nnews = _ctx.NationalNews.ToList();
            nnews.Reverse();
            var nnewsVM = nnews.ToViewModel();
            return View(nnewsVM);
            }
            catch(Exception ex)
            {
                return View ("could not be added !!!");
            }
        }

        // for adding news 

        public IActionResult AddNews()
        {

            return View();
        }

        [HttpPost]
        public IActionResult AddNews(NationalNewsVM nationalNewsVM)
        {

            if (nationalNewsVM == null || !ModelState.IsValid)
            {
                //return View("Error", new ErrorViewModel { RequestId = "Register News" });
                return View();
            }

            string avatarPath = nationalNewsVM.Avatar.SaveNewsImage();
            var nationalNews = nationalNewsVM.ToModel();
            nationalNews.ImageUrl = avatarPath;
            try
            {
                _ctx.Add(nationalNews);
                _ctx.SaveChanges();
                TempData["msg"] = "Added Successfully";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["msg"] = "could not be added !!!";

            }
            return View();
        }


        // for editing and updating news

        public IActionResult EditNationalNews(int id)
        {
            var nnews = _ctx.NationalNews.Find(id);
            var nnewsVM = nnews?.ToViewModel();
            return View(nnewsVM);
        }

        [HttpPost]
        public IActionResult EditNationalNews(NationalNewsVM nationalNewsVM)
        {
            if (nationalNewsVM == null || !ModelState.IsValid)
            {
                return View("Error", new ErrorViewModel { RequestId = "Update NationalNews not successful" });

            }
            var nnews = nationalNewsVM.ToModel();
            if (nationalNewsVM.Avatar is not null)
            {
                var path = nationalNewsVM.Avatar.SaveNewsImage();
                nnews.ImageUrl = path;
            }
            try
            {
                _ctx.NationalNews.Update(nnews);
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["msg"] = "Could not be added";
                return View();
            }
        }




        // for deleting and updating news
        public IActionResult DeleteConfirmNN(int id)
        {
            var nnews = _ctx.NationalNews.Find(id);
            var nnewsVM = nnews?.ToViewModel();
            return View(nnewsVM);
        }

        [HttpPost]
        public IActionResult DeleteNN(NationalNewsVM nationalNewsVM)
        {
            try
            {
                var nnews = nationalNewsVM.ToModel();
                if (nnews != null)
                {
                    _ctx.NationalNews.Remove(nnews);
                    _ctx.SaveChanges();
                }

            }
            catch (Exception ex)
            {
            }
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public IActionResult ReadNationalNews()
        {
            var nnews = _ctx.NationalNews.ToList();
            var nnewsVM = nnews.ToViewModel();

            var ads = _ctx.AdsModel.ToList();
            var adsVM = ads.ToViewModel();
            NationalAdsViewModel navm = new()
            {
                NationalNewsVM = nnewsVM,
                AdsVM = adsVM
            };

            return View(navm);
        }
        [AllowAnonymous]
        public IActionResult ShowNewsInDetail(int id)
        {
            var nnews = _ctx.NationalNews.Where(x => x.NationalNewsId == id).ToList();

            var nnewsVM = nnews.ToViewModel();

            var ads = _ctx.AdsModel.ToList();
            var adsVM = ads.ToViewModel();

            NationalAdsViewModel nav = new()
            {
                NationalNewsVM = nnewsVM,
                AdsVM = adsVM,
            };

            return View(nav);
        }
    }
}

InsiderNepalApp/InsiderNepalApp/Views/NationalNews/AddNews.cshtml
@model InsiderNepalApp.ViewModel.NationalNewsVM;
<nav class="sidenavbar">
    <ul style="margin-top:100px;">
        <li><a asp-controller="NationalNews" asp-action="index"><i class="fa-solid fa-pen-to-square m-2"></i>Edit</a></li>
        <li><a asp-controller="NationalNews" asp-action="index"><i class="fa-solid fa-trash m-2"></i>Delete</a></li>
        <li><a asp-controller="NationalNews" asp-action="addnews"><i class="fa-solid fa-plus m-2"></i>Add</a></li>
    </ul>
</nav>
<div class="navbar-toggle">
    <a id="navbar-toggle" class="btn btn-primary" style="background-color:rgb(11,35,81); position:fixed;right:10px;" href="#"><i class="fa-solid fa-bars"></i></a>
</div>
<div style="padding-bottom:60px"></div>
<div class="newsTopic">
    <div class="text-center h2">Global News</div>
</div>
<form asp-action="AddNews" method="post" class="col g-10" enctype="multipart/form-data">
   
    <h3>Add National News</h3>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-5 col-md-5">
        <label asp-for="Title" class="form-label">News Title</label>
        <input asp-for="Title" type="text" class="form-control">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-8">
        <label asp-for="Content" class="form-label">News Content</label>
        <textarea rows="5"  class="form-control" asp-for="Content" type="text"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>

    <div class="mt-4 col-md-12"></div>
    

    <div class="mb-3 col-md-5">
        <label asp-for="Avatar" class="form-label">News Image</label><br />
        <input class="form-control" asp-for="Avatar">
        <span class="text-danger" asp-validation-for=Content></span>
       
    </div>
   
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-8">
        <label asp-for="PublishDateTime" class="form-label">Publish Date</label>
        <input asp-for="PublishDateTime" type="date" class="form-control">
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-5">
        <label asp-for="Author" class="form-label">Author Name</label>
        <input asp-for="Author" type="text" class="form-control" />
        <span class="text-danger" asp-validation-for="Author"></span>
    </div>
    <div class="mt-4 col-md-12"></div>
    
    <button type="submit" class="btn btn-primary">Publish</button>
</form>



<script>
    const navbarToggle = document.getElementById("navbar-toggle");
    const sideNavbar = document.querySelector(".sidenavbar");

    navbarToggle.addEventListener("click", () => {
        sideNavbar.classList.toggle("active");
    });
</script>

InsiderNepalApp/InsiderNepalApp/Views/NationalNews/DeleteConfirmNN.cshtml
@model  InsiderNepalApp.ViewModel.NationalNewsVM;

<h3 style="color:red; font-family:cursive; margin-left:10%;">Really want to delete?</h3><br />
<div style="margin-left:40%; transform:translate(-50%)">
<form asp-action="DeleteNN" method="post">
    <input type="hidden" asp-for="NationalNewsId" />
    <div class="pb-3 border-bottom" style="width:44rem">

        <div class="d-flex mt-4  col-md-12 col-sm-6 gap-4">
            <div class="col-md-6 col-sm-6">
                <h3 class="card-title" style="font-family:Calibri">@Model.Title</h3>
                <p class="text-black-50">@Model.PublishDateTime.ToString("MMM dd, yyyy")</p>
                    @{
                        string newscontent = string.Join(" ", Model.Content.Split(' ', StringSplitOptions.RemoveEmptyEntries).Take(25)) + " ...";
                    }
                <p style="font-weight:bold">@newscontent</p>
                <p class="text-black-50">- @Model.Author</p>
            </div>
            @*different ways of fitting image in the given dev: fill, contain, cover none, scale-down*@
            <div class="col-md-6 col-sm-6" style="width:300px; height: 220px;">
                <img src="@Model.ImageUrl" class=" col-md-6 h-100 w-100" style="width:100%; height:100%; object-fit:cover; border-radius:10px;" />
            </div>

            @*for edit and delete button *@
        </div>
        <a asp-controller="NationalNews" asp-action="Index" class="btn btn-primary" style="background-color:#00308F">Cancel</a>
        <button type="submit" class="btn btn-danger">Delete</button>
        @*<a class="btn btn-success" style="background-color:rgb(43,97,58)" href="/NationalNews/EditNationalNews?id=@nnews.NationalNewsId">Edit</a>
        <a class="btn btn-danger" style="background-color:rgb(158,3,13)" href="/NationalNews/DeleteConfirmNN?id=@nnews.NationalNewsId">Delete</a>*@
    </div>
</form>
</div>

InsiderNepalApp/InsiderNepalApp/Views/NationalNews/EditNationalNews.cshtml
@model InsiderNepalApp.ViewModel.NationalNewsVM;

<div class="text-center h2" style="font-family:Consolas">Edit National News</div>


<div>
    <div class=" ms-5 d-flex justify-content-center" style="padding-left:5%">
    <form asp-action="EditNationalNews"  method="post" enctype="multipart/form-data">
    <input class="form-control" type="hidden" asp-for="NationalNewsId" />

    <div class="col-sm-8 col-md-10">
        <label asp-for="Title" class="form-label" style="font-weight:bold;">News Title</label>
                <input asp-for="Title" type="text" class="form-control" style="border:1px solid black;border-radius:8px;">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-8 col-md-10">
            <label asp-for="Content" class="form-label" style="font-weight:bold;">News Content</label>
                <textarea rows="5" class="form-control" asp-for="Content" type="text" style="border:1px solid black;border-radius:8px;"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>

    <div class="mt-4 col-md-12"></div>


    <div class="mb-3 col-md-10" >
        <div class="row">
            <div>
                    <label asp-for="Avatar" class="form-label" style="font-weight:bold;">News Image</label><br />
                        <input class="form-control" asp-for="Avatar" style="border:1px solid black;border-radius:8px;">
            </div>
            <div class="mt-4 col-md-12"></div>

            <div>
                <img src="@Model.ImageUrl" style="height:100%; width:100%; border-radius:10px"/>
            </div>
        </div>

    </div>
        <input type="hidden" asp-for="ImageUrl" style="font-weight:bold;" />
    <div class="mt-4 col-md-10"></div>

    <div class="col-sm-8 col-md-10">
            <label asp-for="PublishDateTime" class="form-label" style="font-weight:bold;">Publish Date</label>
                <input asp-for="PublishDateTime" type="date" class="form-control" style="border:1px solid black;border-radius:8px;">
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-5 col-md-10">
            <label asp-for="Author" class="form-label" style="font-weight:bold;">Author Name</label>
                <input asp-for="Author" type="text" class="form-control" style="border:1px solid black;border-radius:8px;" />
        <span class="text-danger" asp-validation-for="Author"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <button type="submit" class="btn btn-primary custom-btn" style="background-color:#00308F">Update</button>
    <a asp-controller="NationalNews" asp-action="Index" class="btn btn-dark custom-btn" style="background-color:#5B3B8C">Back</a>
</form>
    </div>
</div>


@*<table class="table border-primary table-bordered">
   
    <thead>
        <tr>
            <th>News</th>
            <th>Content</th>
            <th>Image</th>
            <th>Publish Date</th>
            <th>Author Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var news in Model)
        {
            <div>
            @{
                string newsContent = string.Join(" ", @news.Content.Split(' ', StringSplitOptions.RemoveEmptyEntries).Take(10));
            }
            </div>

            <tr>
                <td>@news.Title</td>
               <td>@newsContent</td>
                <td><img src="@news.ImageUrl" style="height:50px;"></td>
                <td>@news.PublishDateTime.ToString("ddd, MMM dd yyyy")</td>
                <td>@news.Author</td>
            </tr>
        }
    </tbody>
</table>*@

InsiderNepalApp/InsiderNepalApp/Views/NationalNews/Index.cshtml
@model IEnumerable<InsiderNepalApp.ViewModel.NationalNewsVM>
@{
    ViewData["Title"] = "NationalNews";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title style="font-family:monospace">National News Index</title>
</head>
<body>

    <nav class="sidenavbar">
        <ul style="margin-top:100px;">
            <li><a asp-controller="NationalNews" asp-action="index"><i class="fa-solid fa-pen-to-square m-2"></i>Edit</a></li>
            <li><a asp-controller="NationalNews" asp-action="index"><i class="fa-solid fa-trash m-2"></i>Delete</a></li>
            <li><a asp-controller="NationalNews" asp-action="addnews"><i class="fa-solid fa-plus m-2"></i>Add</a></li>
        </ul>
    </nav>
    <div class="navbar-toggle">
        <a id="navbar-toggle" class="btn btn-primary" style="background-color:rgb(11,35,81); position:fixed;right:10px;" href="#"><i class="fa-solid fa-bars"></i></a>
    </div>



    <div style="padding-bottom:20px"></div>
    <div class="newsTopic">
        <div class="text-center h2">National News</div>
    </div>


   @* @foreach (var nnews in Model)
    {
        <div class="mx-auto pb-3 border-bottom" style="width:50rem">
            <div class="mx-auto d-flex mt-5  col-12 col-sm-6 col-md-6 gap-2" style="width:50rem;">
                <div class="col-md-6 col-sm-6">
                    <div class="newsHeadLine">
                        <h3 class="card-title">@nnews.Title</h3>
                    </div>
                    <div class="dateAndAuthor">
                        <p class="text-black-50">@nnews.PublishDateTime.ToString("MMM dd, yyyy")</p>
                    </div>  
                    <div class="newsContent">

                        <p style="font-weight:bold">
                            @{string selectWords = string.Join(" ", @nnews.Content.Split(' ', StringSplitOptions.RemoveEmptyEntries).Take(80))+" . . . . . .";
                        }</p>
                        @selectWords
                    </div>
                    <div class="dateAndAuthor">
                        <p class="text-black-50">- @nnews.Author</p>
                    </div>
                </div>

                <div class="col-md-6 col-sm-6" style="width:300px; height: 220px;">
                    <img src="@nnews.ImageUrl" class=" col-md-6 h-100 w-100" style="width:100%; height:100%; object-fit:cover; border-radius:10px;" />
                </div>
            </div>
            <a asp-controller="NationalNews" asp-action="EditNationalNews" asp-route-id="@nnews.NationalNewsId" class="btn btn-success" style="background-color:rgb(43,97,58)">Edit</a>
            <a class="btn btn-danger" style="background-color:rgb(158,3,13)" href="/NationalNews/DeleteConfirmNN?id=@nnews.NationalNewsId">Delete</a>

        </div>

    }*@
    <table class="table border-primary table-bordered">

        <thead>
            <tr>
                <th>S.N</th>
                <th>News</th>
                <th>Content</th>
                <th>Image</th>
                <th>Publish Date</th>
                <th>Author Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
               @{var i =1;}
            @foreach (var news in Model)
            {
                <div>
                    @{
                        string newsContent = string.Join(" ", @news.Content.Split(' ', StringSplitOptions.RemoveEmptyEntries).Take(10))+" ....";
                    }
                </div>

                <tr>
                    <td>@i</td>
                    <td>@news.Title</td>
                    <td>@newsContent</td>
                    <td><img src="@news.ImageUrl" style="height:50px;"></td>
                    <td>@news.PublishDateTime.ToString("ddd, MMM dd yyyy")</td>
                    <td>@news.Author</td>
                   <td> <a asp-controller="NationalNews" asp-action="EditNationalNews" asp-route-id="@news.NationalNewsId" class="btn btn-success" style="background-color:rgb(43,97,58)">Edit</a>
                    <a class="btn btn-danger" style="background-color:rgb(158,3,13)" href="/NationalNews/DeleteConfirmNN?id=@news.NationalNewsId">Delete</a>
                    </td>
                </tr>
                <div>
                @{
                    i++;
                }
                </div>
            }
        </tbody>
        </table>
    <script>
        const navbarToggle = document.getElementById("navbar-toggle");
        const sideNavbar = document.querySelector(".sidenavbar");

        navbarToggle.addEventListener("click", () => {
            sideNavbar.classList.toggle("active");
        });
    </script>

</body>
</html>

InsiderNepalApp/InsiderNepalApp/Views/NationalNews/ReadNationalNews.cshtml
@model InsiderNepalApp.ViewModel.NationalAdsViewModel;

@{
    ViewData["Title"] = "NationalNews";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <title style="font-family:monospace">National News Index</title>
</head>
<body>


    <div>
        <img src="@Model.AdsVM[9].ImageUrl" style="margin-left:50%; transform:translate(-50%);" />
    </div>

    <div style="padding-bottom:40px"></div>
    <div class="newsTopic">
        <div class="text-center h2">National News</div>
    </div>

    <div class="col-md-12 ms-4 row gap-0">
        <div class="mx-auto col-md-12 col-lg-6  col-sm-12">
            @foreach (var nnews in Model.NationalNewsVM)
            {
                <div class="d-flex mt-5 pb-5 col-md-12 col-sm-12 gap-3 border-bottom">
                    <div class="col-md-6 col-sm-6">
                        <div class="newsHeadLine">
                            @{
                                string newsTitle = string.Join(" ", @nnews.Title.Split(' ', StringSplitOptions.RemoveEmptyEntries).Take(6)) + "...";
                            }
                            <h3 class="card-title">@newsTitle</h3>
                        </div>
                        <div class="dateAndAuthor">
                            <p class="text-black-50">@nnews.PublishDateTime.ToString("MMM dd, yyyy")</p>
                        </div>
                        <div class="newsSubContent" style="font-weight:bold">
                            <p>
                                @{
                                    string selectWords = string.Join(" ", @nnews.Content.Split(' ', StringSplitOptions.RemoveEmptyEntries).Take(20)) + "...";
                                }
                            </p>
                            @selectWords <a asp-controller="NationalNews" asp-action="ShowNewsInDetail" asp-route-id="@nnews.NationalNewsId" style="color:deepskyblue">Readmore</a>
                        </div>
                        
                        <div class="dateAndAuthor">
                            <p class="text-black-50">- @nnews.Author</p>
                        </div>
                    </div>
                    @*different ways of fitting image in the given dev: fill, contain, cover none, scale-down*@
                    <div class="col-md-6 col-sm-6">
                        <img src="@nnews.ImageUrl" style="width:100%;height:100%; width:340px; height:230px; object-fit:cover; border-radius:10px;" />
                    </div>
                </div>
          

            }
        </div>
        <div class="col-md-3 col-lg-4 mt-5 border-bottom" style="transform:translateX(-20%);">
            @for(int i= 0; i<Model.NationalNewsVM.Count/2; i++)
            {
                <div class="mb-5 pb-5"><img src="@Model.AdsVM[i].ImageUrl" style="margin-bottom:40px; width:400px;height:220px; object-fit:cover; border-radius:10px"> </div>

            }
         
        </div>
    </div>
    <div class="mb-5"></div>
    <div>
        <img src="@Model.AdsVM[10].ImageUrl" style="margin-left:50%; transform:translate(-50%);" />
    </div>
</body>
</html>

InsiderNepalApp/InsiderNepalApp/Views/NationalNews/ShowNewsInDetail.cshtml
@model InsiderNepalApp.ViewModel.NationalAdsViewModel;
@{
    ViewData["Title"] = "NationalNews In Detail";
}
<div class="border-1 border-black">
<img src="@Model.AdsVM[9].ImageUrl" style="margin-left:50%;transform:translate(-50%);"/>
</div>
<div class="mt-5"></div>
@foreach(var nnews in Model.NationalNewsVM)
{
    
<div class="col-md-9  mx-auto">
    <div class="newsHeadLine"><h2>@nnews.Title</h2></div>
    <div class="dateAndAuthor" st yle="font-size:12px;opacity:0.7">@nnews.Author</div>
    <div class="dateAndAuthor">
        <p class="text-black-50">@nnews.PublishDateTime.ToString("MMM dd, yyyy")</p>
    </div>

    <div class="col-md-8 col-sm-12 mx-auto">
        <img src="@nnews.ImageUrl" class="h-100 w-100" style="width:650px; height:480px;object-fit:cover;border-radius:5px;">
    </div>
    <div class="mt-5"></div>
    <div class="newsContent" style="word-spacing:0.2rem;line-height:1.5; font-size:1.1rem; letter-spacing:0.0001776464rem;word-break:break-all;">@nnews.Content</div>
</div> 
}
<div class="mt-5"></div>
<div class="col-md-9 mx-auto"></div>
<img src="@Model.AdsVM[10].ImageUrl" style="margin-left:50%;transform:translate(-50%);"/>