InsiderNepalApp/InsiderNepalApp/Models/BussinessNews.cs
using System.ComponentModel.DataAnnotations;

namespace InsiderNepalApp.Models
{
    public class BussinessNews
    {
        [Key]
        public int BussinessNewsId { get; set; }

        public string? Title { get; set; }


        public string? Author { get; set; }



        public DateTime PublishDateTime { get; set; }


        public string? Content { get; set; }


        public string? ImageUrl { get; set; }

    }
}

InsiderNepalApp/InsiderNepalApp/Controllers/BussinessNewsController.cs
using InsiderNepalApp.Data;
using InsiderNepalApp.Extensions;
using InsiderNepalApp.Mapper;
using InsiderNepalApp.Models;
using InsiderNepalApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace InsiderNepalApp.Controllers;

[Authorize(Roles ="Admin")]
public class BussinessNewsController : Controller
{

    private readonly InsiderNepalDbContext _bdx;
    public BussinessNewsController(InsiderNepalDbContext bdx)
    {
        _bdx = bdx;
    }
    public IActionResult Index()
    {
        var bnews = _bdx.BussinessNews.ToList();
        bnews.Reverse();
        var bnewsVM = bnews.ToViewModel();
        return View(bnewsVM);
    }

    //Add BussinessNews 
    public IActionResult AddBussinessNews()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddBussinessNews(BussinessNewsVM bnewsVM)
    {
        if (bnewsVM == null || !ModelState.IsValid)
        {
            return View();
        }

        string avatarPath = bnewsVM.Avatar.SaveBussinessImage();
        var bNews = bnewsVM.ToModel();
        bNews.ImageUrl = avatarPath;
        try
        {
            _bdx.Add(bNews);
            _bdx.SaveChanges();
            TempData["msg"] = "Added Successfully";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["msg"] = "could not be added !!!";

        }
        return View();
    }

    //For editing the news
    public IActionResult EditBussinessNews(int id)
    {
        var bNews = _bdx.BussinessNews.Find(id);
        var bNewsVM = bNews.ToViewModel();
        return View(bNewsVM);
    }

    [HttpPost]
    public IActionResult EditBussinessNews(BussinessNewsVM bNewsVM)
    {
        if (bNewsVM == null || !ModelState.IsValid)
        {
            return View();
        }
        var bNews = bNewsVM.ToModel();
        if (bNewsVM.Avatar is not null)
        {
            var path = bNewsVM.Avatar.SaveBussinessImage();
            bNews.ImageUrl = path;
        }
        try
        {
            _bdx.BussinessNews.Update(bNews);
            _bdx.SaveChanges();
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["msg"] = "Could not be added";
            return View();
        }
    }

    //For Delete confirm

    public IActionResult DeleteConfirmBN(int id)
    {
        var bNews = _bdx.BussinessNews.Find(id);
        var bNewsVM = bNews.ToViewModel();
        return View(bNewsVM);
    }

    [HttpPost]
    public IActionResult DeleteBN(BussinessNewsVM bNewsVM)

    {
        try
        {
            var bnews = bNewsVM.ToModel();
            if (bnews != null)
            {
                _bdx.Remove(bnews);
                _bdx.SaveChanges();

            }
        }
        catch (Exception ex)
        {
        }
        return RedirectToAction("Index");
    }


    [AllowAnonymous]
    public IActionResult ReadBussinessNews()
    {
        var gnews = _bdx.BussinessNews.ToList();
        gnews.Reverse();

        var gnewsVM = gnews.ToViewModel();

        var ads = _bdx.AdsModel.ToList();
        var adsVM = ads.ToViewModel();
        BussinessAdsVM gav = new()
        {
            BussinessNewsVM = gnewsVM,
            AdsVM = adsVM,
        };

        return View(gav);
    }

    [AllowAnonymous]
    public IActionResult ShowBussinessInDetail(int id)
    {
        var gnews = _bdx.BussinessNews.Where(x => x.BussinessNewsId == id).ToList();
        var gnewsVM = gnews.ToViewModel();

        var ads = _bdx.AdsModel.ToList();
        var adsVM = ads.ToViewModel();

        BussinessAdsVM gav = new()
        {
            BussinessNewsVM = gnewsVM,
            AdsVM = adsVM
        };

        return View(gav);
    }
}

InsiderNepalApp/InsiderNepalApp/Controllers/GlobalNewsController.cs
using InsiderNepalApp.Data;
using InsiderNepalApp.Extensions;
using InsiderNepalApp.Mapper;
using InsiderNepalApp.Models;
using InsiderNepalApp.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Identity.Client;

namespace InsiderNepalApp.Controllers;

[Authorize(Roles = "Admin")]
public class GlobalNewsController : Controller
{
    private readonly InsiderNepalDbContext _gdx;
    public GlobalNewsController(InsiderNepalDbContext gdx)
    {
        _gdx = gdx;
    }
    public IActionResult Index()
    {
        var globalNews = _gdx.GlobalNews.ToList();
        globalNews.Reverse();
        var globalNewsVM = globalNews.ToViewModel();
        return View(globalNewsVM);
    }

    public IActionResult AddGlobalNews()
    {
        return View();
    }

    [HttpPost]
    public IActionResult AddGlobalNews(GlobalNewsVM globalNewsVM)
    {
        if (globalNewsVM == null || !ModelState.IsValid)
        {
            //return View("Error", new ErrorViewModel {RequestId = "Registering Global News is not possible !!"});
            return View();
        }
        string imagePath = globalNewsVM.Avatar.SaveGlobalImage();
        var globalNews = globalNewsVM.ToModel();
        globalNews.ImageUrl = imagePath;

        try
        {
            _gdx.Add(globalNews);
            _gdx.SaveChanges();
            TempData["msg"] = "Added Successfully";
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            TempData["msg"] = "could not be added !!";
        }
        return View();
    }


    // for editing 

    public IActionResult EditGlobalNews(int id)
    {
        var gNews = _gdx.GlobalNews.Find(id);
        var gNewsVM = gNews.ToViewModel();
        return View(gNewsVM);
    }

    [HttpPost]
    public IActionResult EditGlobalNews(GlobalNewsVM globalNewsVM)
    {
        if (globalNewsVM == null || !ModelState.IsValid)
        {
            return View("Error", new ErrorViewModel { RequestId = "Update Global news not successful" });
        }

        var gNews = globalNewsVM?.ToModel();
        if (globalNewsVM?.Avatar != null)
        {
            var path = globalNewsVM.Avatar.SaveGlobalImage();
            gNews.ImageUrl = path;
        }
        try
        {
            _gdx.GlobalNews.Update(gNews);
            _gdx.SaveChanges();
            return RedirectToAction("Index");
        }
        catch (Exception ex) { }
        {
            TempData["msg"] = "could not be added";
            return View();
        }

    }
    //for deleting

    public IActionResult DeleteConfirm(int id)
    {
        var gnews = _gdx.GlobalNews.Find(id);
        var gnewsVM = gnews.ToViewModel();
        return View(gnewsVM);
    }

    [HttpPost]
    public IActionResult DeleteGlobalNews(GlobalNewsVM globalNewsVM)
    {
        try
        {
            var gnews = globalNewsVM.ToModel();
            if (gnews != null)
            {
                _gdx.GlobalNews.Remove(gnews);
                _gdx.SaveChanges();
            }
        }
        catch (Exception ex)
        {

        }
        return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public IActionResult ReadGlobalNews()
    {
        var gnews = _gdx.GlobalNews.ToList();
        gnews.Reverse();

        var gnewsVM = gnews.ToViewModel();

        var ads = _gdx.AdsModel.ToList();
        var adsVM = ads.ToViewModel();
        GlobalAdsVM gav = new()
        {
            GlobalNewsVM = gnewsVM,
            AdsVM = adsVM,
        };

        return View(gav);
    }

    [AllowAnonymous]
    public IActionResult ShowGlobalInDetail(int id)
    {
        var gnews = _gdx.GlobalNews.Where(x=>x.GlobalId == id).ToList();
        var gnewsVM = gnews.ToViewModel();

        var ads = _gdx.AdsModel.ToList();
        var adsVM = ads.ToViewModel();

        GlobalAdsVM gav = new()
        {GlobalNewsVM = gnewsVM,
            AdsVM = adsVM};

        return View(gav);
    }
}

InsiderNepalApp/InsiderNepalApp/Views/BussinessNews/AddBussinessNews.cshtml
@model InsiderNepalApp.ViewModel.BussinessNewsVM;
<nav class="sidenavbar">
    <ul style="margin-top:100px;">
        <li><a asp-controller="BussinessNews" asp-action="Index"><i class="fa-solid fa-pen-to-square m-2"></i>Edit</a></li>
        <li><a asp-controller="BussinessNews" asp-action="Index"><i class="fa-solid fa-trash m-2"></i>Delete</a></li>
        <li><a asp-controller="BussinessNews" asp-action="AddBussinessNews"><i class="fa-solid fa-plus m-2"></i>Add</a></li>
    </ul>
</nav>
<div class="navbar-toggle">
    <a id="navbar-toggle" class="btn btn-primary" style="background-color:rgb(11,35,81); position:fixed;right:10px;" href="#"><i class="fa-solid fa-bars"></i></a>
</div>
<div style="padding-bottom:60px"></div>
<div class="newsTopic">
    <div class="text-center h2">Global News</div>
</div>
<form asp-action="AddBussinessNews" method="post" class="col g-10" enctype="multipart/form-data">

    <h3>Add Bussiness News</h3>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-5 col-md-5">
        <label asp-for="Title" class="form-label">News Title</label>
        <input asp-for="Title" type="text" class="form-control">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-8">
        <label asp-for="Content" class="form-label">News Content</label>
        <textarea rows="5" class="form-control" asp-for="Content" type="text"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>

    <div class="mt-4 col-md-12"></div>


    <div class="mb-3 col-md-5">
        <label asp-for="Avatar" class="form-label">News Image</label><br />
        <input class="form-control" asp-for="Avatar">
        <span class="text-danger" asp-validation-for=Content></span>

    </div>

    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-8">
        <label asp-for="PublishDateTime" class="form-label">Publish Date</label>
        <input asp-for="PublishDateTime" type="date" class="form-control">
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-5">
        <label asp-for="Author" class="form-label">Author Name</label>
        <input asp-for="Author" type="text" class="form-control" />
        <span class="text-danger" asp-validation-for="Author"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <button type="submit" class="btn btn-primary">Publish</button>
</form>



<script>
    const navbarToggle = document.getElementById("navbar-toggle");
    const sideNavbar = document.querySelector(".sidenavbar");

    navbarToggle.addEventListener("click", () => {
        sideNavbar.classList.toggle("active");
    });
</script>

InsiderNepalApp/InsiderNepalApp/Views/BussinessNews/DeleteConfirmBN.cshtml
@*@model InsiderNepalApp.ViewModel.BussinessNewsVM;

<h3>You sure, want to delete @Model.Title news permanently?</h3>
<br />

<form asp-action="DeleteBN" method="post">
    <input type="hidden" asp-for="BussinessNewsVMId" />
    <div class="pb-3 border-bottom" style="width:44rem">

        <div class="d-flex mt-5  col-12 col-sm-6 col-md-6" style="width:50rem;">
            <div class="col-md-6 col-sm-6">
                <h3 class="card-title" style="font-family:Calibri">@Model.Title</h3>
                <p class="text-black-50">@Model.PublishDateTime.ToString("MMM dd, yyyy")</p>
                <p style="font-weight:bold">@Model.Content</p>
                <p class="text-black-50">- @Model.Author</p>
            </div>
            @*different ways of fitting image in the given dev: fill, contain, cover none, scale-down
            <div class="col-md-6 col-sm-6" style="width:300px; height: 220px;">
                <img src="@Model.ImageUrl" class=" col-md-6 h-100 w-100" style="width:100%; height:100%; object-fit:cover; border-radius:10px;" />
            </div>

            @*for edit and delete button 
        </div>
        <a asp-controller="BussinessNews" asp-action="Index" class="btn btn-primary" style="background-color:#00308F">Cancel</a>
        <button type="submit" class="btn btn-danger">Delete</button>
        @*<a class="btn btn-success" style="background-color:rgb(43,97,58)" href="/NationalNews/EditNationalNews?id=@nnews.NationalNewsId">Edit</a>
        <a class="btn btn-danger" style="background-color:rgb(158,3,13)" href="/NationalNews/DeleteConfirmNN?id=@nnews.NationalNewsId">Delete</a>
    </div>
</form>*@


@model InsiderNepalApp.ViewModel.BussinessNewsVM;
<div style="font-family:cursive; margin-left:10%;">
    <h3 style="color: red;">Really Want to delete ? </h3>
</div>
<div style="margin-left:40%; transform:translate(-50%);">
    <form asp-action="DeleteBN" method="post">
        <input type="hidden" asp-for="BussinessNewsVMId" />
        <div class="pb-3 border-bottom">

            <div class="d-flex mt-4 col-md-12 col-sm-6 gap-4">
                <div class="col-md-6 col-sm-6">
                    <h3 class="card-title" style="font-family:Calibri">@Model.Title</h3>
                    <p class="text-black-50">@Model.PublishDateTime.ToString("MMM dd, yyyy")</p>
                    @{
                        string newscontent = string.Join(" ", Model.Content.Split(' ', StringSplitOptions.RemoveEmptyEntries).Take(25)) + " ...";
                    }
                    <p style="font-weight:bold">@newscontent</p>
                    <p class="text-black-50">- @Model.Author</p>
                </div>
                @*different ways of fitting image in the given dev: fill, contain, cover none, scale-down*@
                <div class="col-md-6 col-sm-6" style="width:300px; height: 220px;">
                    <img src="@Model.ImageUrl" class=" col-md-6 h-100 w-100" style="width:100%; height:100%; object-fit:cover; border-radius:10px;" />
                </div>

                @*for edit and delete button *@
            </div>
            <a asp-controller="GlobalNews" asp-action="Index" class="btn btn-primary" style="background-color:#00308F">Cancel</a>
            <button type="submit" class="btn btn-danger">Delete</button>
            @*<a class="btn btn-success" style="background-color:rgb(43,97,58)" href="/NationalNews/EditNationalNews?id=@nnews.NationalNewsId">Edit</a>
            <a class="btn btn-danger" style="background-color:rgb(158,3,13)" href="/NationalNews/DeleteConfirmNN?id=@nnews.NationalNewsId">Delete</a>*@
        </div>
    </form>
</div>

InsiderNepalApp/InsiderNepalApp/Views/BussinessNews/EditBussinessNews.cshtml
@model InsiderNepalApp.ViewModel.BussinessNewsVM;


@*<div class="text-center h2" style="font-family:Consolas">Edit Bussiness News</div>

<form asp-action="EditBussinessNews" method="post" enctype="multipart/form-data">
    <input class="form-control" type="hidden" asp-for="BussinessNewsVMId" />

    <div class="col-sm-5">
        <label asp-for="Title" class="form-label">News Title</label>
        <input asp-for="Title" type="text" class="form-control">
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-8">
        <label asp-for="Content" class="form-label">News Content</label>
        <textarea rows="5" class="form-control" asp-for="Content" type="text"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>

    <div class="mt-4 col-md-12"></div>


    <div class="mb-3 col-md-5">
        <div class="row">
            <div>
                <label asp-for="Avatar" class="form-label">News Image</label><br />
                <input class="form-control" asp-for="Avatar">
            </div>
            <div class="mt-4 col-md-12"></div>

            <div>
                <img src="@Model.ImageUrl" style="height:100%; width:100%; border-radius:10px" />
            </div>
        </div>

    </div>
    <input type="hidden" asp-for="ImageUrl" />
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-8">
        <label asp-for="PublishDateTime" class="form-label">Publish Date</label>
        <input asp-for="PublishDateTime" type="date" class="form-control">
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <div class="col-sm-5">
        <label asp-for="Author" class="form-label">Author Name</label>
        <input asp-for="Author" type="text" class="form-control" />
        <span class="text-danger" asp-validation-for="Author"></span>
    </div>
    <div class="mt-4 col-md-12"></div>

    <button type="submit" class="btn btn-primary custom-btn" style="background-color:#00308F">Update</button>
    <a asp-controller="BussinessNews" asp-action="Index" class="btn btn-dark custom-btn" style="background-color:#5B3B8C">Back</a>
</form>
*@



<div class="text-center h2" style="font-family:Consolas">Edit Bussiness News</div>
<div>
    <div class=" ms-5 d-flex justify-content-center" style="padding-left:5%;">
        <form asp-action="EditGlobalNews" method="post" enctype="multipart/form-data">
            <input class="form-control" type="hidden" asp-for="BussinessNewsVMId" />

            <div class="col-sm-8 col-md-10">
                <label asp-for="Title" class="form-label" style="font-weight:bold;">News Title</label>
                <input asp-for="Title" type="text" class="form-control" style="border:1px solid black;border-radius:8px;">
                <span class="text-danger" asp-validation-for="Title"></span>
            </div>
            <div class="mt-4 col-md-12"></div>

            <div class="col-sm-8 col-md-10">
                <label asp-for="Content" class="form-label" style="font-weight:bold;">News Content</label>
                <textarea rows="5" class="form-control" asp-for="Content" type="text" style="border:1px solid black;border-radius:8px;"></textarea>
                <span class="text-danger" asp-validation-for="Content"></span>
            </div>

            <div class="mt-4 col-md-12"></div>


            <div class="mb-3 col-md-10">
                <div class="row">
                    <div>
                        <label asp-for="Avatar" class="form-label" style="font-weight:bold;">News Image</label><br />
                        <input class="form-control" asp-for="Avatar" style="border:1px solid black;border-radius:8px;">
                    </div>
                    <div class="mt-4 col-md-12"></div>

                    <div>
                        <img src="@Model.ImageUrl" style="height:100%; width:100%; border-radius:10px" />
                    </div>
                </div>

            </div>
            <input type="hidden" asp-for="ImageUrl" style="border:1px solid black;" />
            <div class="mt-4 col-md-12"></div>

            <div class="col-sm-8 col-md-10">
                <label asp-for="PublishDateTime" class="form-label" style="font-weight:bold;">Publish Date</label>
                <input asp-for="PublishDateTime" type="date" class="form-control" style="border:1px solid black;border-radius:8px;">
                <span class="text-danger" asp-validation-for="Content"></span>
            </div>
            <div class="mt-4 col-md-12"></div>

            <div class="col-sm-5 col-md-10">
                <label asp-for="Author" class="form-label" style="font-weight:bold;">Author Name</label>
                <input asp-for="Author" type="text" class="form-control" style="border:1px solid black;border-radius:8px;" />
                <span class="text-danger" asp-validation-for="Author"></span>
            </div>
            <div class="mt-4 col-md-12"></div>

            <button type="submit" class="btn btn-primary custom-btn" style="background-color:#00308F">Update</button>
            <a asp-controller="GlobalNews" asp-action="index" class="btn btn-dark custom-btn" style="background-color:#5B3B8C">Back</a>
        </form>
    </div>
</div>

InsiderNepalApp/InsiderNepalApp/Views/BussinessNews/Index.cshtml
@model IEnumerable<InsiderNepalApp.ViewModel.BussinessNewsVM>
@{
    ViewData["Title"] = "Bussiness";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title style="font-family:monospace">Bussiness News Index</title>
</head>
<body>

    <nav class="sidenavbar">
        <ul style="margin-top:100px;">
            <li><a asp-controller="BussinessNews" asp-action="index"><i class="fa-solid fa-pen-to-square m-2"></i>Edit</a></li>
            <li><a asp-controller="BussinessNews" asp-action="index"><i class="fa-solid fa-trash m-2"></i>Delete</a></li>
            <li><a asp-controller="BussinessNews" asp-action="AddBussinessNews"><i class="fa-solid fa-plus m-2"></i>Add</a></li>
        </ul>
    </nav>
    <div class="navbar-toggle">
        <a id="navbar-toggle" class="btn btn-primary" style="background-color:rgb(11,35,81); position:fixed;right:10px;" href="#"><i class="fa-solid fa-bars"></i></a>
    </div>



    <div style="padding-bottom:20px"></div>
    <div class="newsTopic">
        <div class="text-center h2">Bussiness News</div>
    </div>

    <table class="table border-primary table-bordered">

        <thead>
            <tr>
                <th>S.N</th>
                <th>News</th>
                <th>Content</th>
                <th>Image</th>
                <th>Publish Date</th>
                <th>Author Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                var i = 1;
            }
            @foreach (var news in Model)
            {
                <div>
                    @{
                        string newsContent = string.Join(" ", @news.Content.Split(' ', StringSplitOptions.RemoveEmptyEntries).Take(10)) + " ....";
                    }
                </div>

                <tr>
                    <td>@i</td>
                    <td>@news.Title</td>
                    <td>@newsContent</td>
                    <td><img src="@news.ImageUrl" style="height:50px;"></td>
                    <td>@news.PublishDateTime.ToString("ddd, MMM dd yyyy")</td>
                    <td>@news.Author</td>
                    <td>
                        <a asp-controller="BussinessNews" asp-action="EditBussinessNews" asp-route-id="@news.BussinessNewsVMId" class="btn btn-success" style="background-color:rgb(43,97,58)">Edit</a>
                        <a class="btn btn-danger" style="background-color:rgb(158,3,13)" href="/BussinessNews/DeleteConfirmBN?id=@news.BussinessNewsVMId">Delete</a>
                    </td>
                </tr>
                <div>
                    @{
                        i++;
                    }
                </div>
            }
        </tbody>
    </table>
    @*@foreach (var nnews in Model)
    {
        <div class="pb-3 border-bottom" style="width:44rem">
            <div class="d-flex mt-5  col-12 col-sm-6 col-md-6 gap-2" style="width:50rem;">
                <div class="col-md-6 col-sm-6">
                    <div class="newsHeadLine">
                        <h3 class="card-title">@nnews.Title</h3>
                    </div>
                    <div class="dateAndAuthor">
                        <p class="text-black-50">@nnews.PublishDateTime.ToString("MMM dd, yyyy")</p>
                    </div>
                    <div class="newsContent">

                        <p style="font-weight:bold">@nnews.Content</p>
                    </div>
                    <div class="dateAndAuthor">
                        <p class="text-black-50">- @nnews.Author</p>
                    </div>
                </div>
                different ways of fitting image in the given dev: fill, contain, cover none, scale-down
                <div class="col-md-6 col-sm-6" style="width:300px; height: 220px;">
                    <img src="@nnews.ImageUrl" class=" col-md-6 h-100 w-100" style="width:100%; height:100%; object-fit:cover; border-radius:10px;" />
                </div>

                @*for edit and delete button 
            </div>
            <a asp-controller="BussinessNews" asp-action="EditBussinessNews" asp-route-id="@nnews.BussinessNewsVMId" class="btn btn-success" style="background-color:rgb(43,97,58)">Edit</a>
            <a class="btn btn-danger" style="background-color:rgb(158,3,13)" href="/BussinessNews/DeleteConfirmBN?id=@nnews.BussinessNewsVMId">Delete</a>
        </div>

    }*@

    <script>
        const navbarToggle = document.getElementById("navbar-toggle");
        const sideNavbar = document.querySelector(".sidenavbar");

        navbarToggle.addEventListener("click", () => {
            sideNavbar.classList.toggle("active");
        });
    </script>

</body>
</html>

InsiderNepalApp/InsiderNepalApp/Views/BussinessNews/ShowBussinessInDetail.cshtml
@model InsiderNepalApp.ViewModel.BussinessAdsVM;
@{
    ViewData["Title"] = "BussinessNews In Detail";
}
<div class="border-1 border-black">
    <img src="@Model.AdsVM[13].ImageUrl" style="margin-left:50%;transform:translate(-50%);" />
</div>
<div class="mt-5"></div>
@foreach (var nnews in Model.BussinessNewsVM)
{

    <div class="col-md-9  mx-auto">
        <div class="newsHeadLine"><h2>@nnews.Title</h2></div>
        <div class="dateAndAuthor" st yle="font-size:12px;opacity:0.7">@nnews.Author</div>
        <div class="dateAndAuthor">
            <p class="text-black-50">@nnews.PublishDateTime.ToString("MMM dd, yyyy")</p>
        </div>

        <div class="col-md-8 col-sm-12 mx-auto">
            <img src="@nnews.ImageUrl" class="h-100 w-100" style="width:650px; height:480px;object-fit:cover;border-radius:5px;">
        </div>
        <div class="mt-5"></div>
        <div class="newsContent" style="word-spacing:0.2rem;line-height:1.5; font-size:1.1rem; letter-spacing:0.0001776464rem;word-break:break-all;">@nnews.Content</div>
    </div>
}
<div class="mt-5"></div>
<div class="col-md-9 mx-auto"></div>
<img src="@Model.AdsVM[14].ImageUrl" style="margin-left:50%;transform:translate(-50%);" />